#!/usr/bin/env python
import sys
from xremap.dsl import xremap_config
from yaml import dump

def eval_file(path):
    with open(path, 'rb') as file:
        exec(compile(file.read(), path, 'exec'), globals())

if len(sys.argv) != 2:
    print("Usage: xremap-python config.py")
    sys.exit(1)

eval_file(sys.argv[1])

print(dump(xremap_config()))
